### ISSUE TITLE
no net → 'GoogletasksWindow' object has no attribute 'controller'

### ISSUE THREAD

**Issue by e3rd** [e3rd/zim-plugin-googletasks#10]
**maybe when there is no connection at startup**
  File "/home/edvard/.local/share/zim/plugins/googletasks.py", line 294, in import_tasks
	self.controller.fetch()
AttributeError: 'GoogletasksWindow' object has no attribute 'controller'

**Comment by e3rd** [comment]
let's just catch it and put the info to the status bar

**Comment by mechaprabal** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 157, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/home/user/.local/share/zim/plugins/googletasks.py", line 307, in import_tasks
    self.controller.fetch(force=True)
AttributeError: 'GoogletasksWindow' object has no attribute 'controller'

**Comment by e3rd** [comment]
Hello, I might have fixed this bug in [startup bugfix commit](https://github.com/e3rd/zim-plugin-googletasks/releases/tag/0.68) which is the actual release. It is the last release that support Zim 0.68 and less. The other commit from yesterday support only ['Zim next' branch](https://github.com/jaap-karssenberg/zim-desktop-wiki/tree/next) which is not yet merged into master Zim but I wanted this extension to be ready when it becomes merged.

**What commit (what version) of this extension are you using?**
