### ISSUE TITLE
AttributeError: 'GoogletasksWindow' object has no attribute 'controller'

### ISSUE THREAD

**Issue by AlekzNet** [e3rd/zim-plugin-googletasks#18]
Can be related to https://github.com/e3rd/zim-plugin-googletasks/issues/10 It happens when I click Add/Import New tasks or Tasks from cursor:

```text
This is zim 0.72.1
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 8, 2, 'final', 0)
PyGObject: (3, 36, 0)

======= Traceback =======
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 115, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 98, in func
    return self.func(instance, *args, **kwargs)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 260, in add_new_task
    self.gui.setController(self.controller)
AttributeError: 'GoogletasksWindow' object has no attribute 'controller'
```

**Comment by e3rd** [comment]
Thanks for good report, I'll try to debug this in few days

**Comment by e3rd** [comment]
Hi, I've been trying to simulate this but with no luck, it works for me. Would you be so kind, launch the zim with `zim --debug --standalone`, replicate the bug and then copy the output here? There might be more hints in the log.

**Comment by AlekzNet** [comment]
This is what I got:

During the start:

```txt
...
DEBUG: Load extension: <class 'zim.plugins.googletasks.GoogletasksWindow'>
...
DEBUG: Google tasks page: Tasks 
DEBUG: URL being requested: GET https://www.googleapis.com/tasks/v1/lists/%40default/tasks?maxResults=999&showCompleted=false&dueMin=2020-05-25T00%3A00%3A00.000Z&dueMax=2020-05-26T00%3A00%3A00.000Z&alt=json
INFO: Refreshing due to a 401 (attempt 1/2)
INFO: Refreshing access_token
INFO: Googletasks \ No task lists found.
ERROR: Failed loading extension <class 'zim.plugins.googletasks.GoogletasksWindow'> for plugin <zim.plugins.googletasks.GoogletasksPlugin object at 0x7feff5ea84f0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/__init__.py", line 444, in _extend
    ext = ext_class(plugin, obj)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 212, in __init__
    GoogletasksCommand("--plugin googletasks").run()
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 113, in run
    GoogletasksController(notebook=ntb, preferences=GoogletasksCommand.preferences).fetch()  # add new lines
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 588, in fetch
    os.utime(CACHEFILE, None)  # we touch the file
FileNotFoundError: [Errno 2] No such file or directory
```

Then after clicking on Add/Import New tasks or Tasks from cursor

```txt
DEBUG: Action: add_new_task
ERROR: Exception during action: add_new_task
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 115, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 98, in func
    return self.func(instance, *args, **kwargs)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 260, in add_new_task
    self.gui.setController(self.controller)
AttributeError: 'GoogletasksWindow' object has no attribute 'controller'
DEBUG: Running ErrorDialog
```

```txt
DEBUG: Action: import_tasks
ERROR: Exception during action: import_tasks
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 115, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 98, in func
    return self.func(instance, *args, **kwargs)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 318, in import_tasks
    self.controller.fetch(force=True)
AttributeError: 'GoogletasksWindow' object has no attribute 'controller'
DEBUG: Running ErrorDialog
```

```txt
INFO: Running: ('git', 'status', '--porcelain') (cwd: '/home/alekz/Notebooks/Notes')
DEBUG: No autosave version needed - no changes
DEBUG: Action: send_as_task
ERROR: Exception during action: send_as_task
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 115, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 98, in func
    return self.func(instance, *args, **kwargs)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 253, in send_as_task
    task = self.controller.readTaskFromSelection()
AttributeError: 'GoogletasksWindow' object has no attribute 'controller'
DEBUG: Running ErrorDialog
```

**Comment by e3rd** [comment]
Great! Very interesting is the first one `FileNotFoundError: [Errno 2] No such file or directory` Would you please try `Claim write access` first? What does it do?

**Comment by e3rd** [comment]
I see that `zim` changed recently the menu system, all the plugin menu items ended in the Tools menu (and not in a submenu) and the user is now seemingly allowed to import tasks without claiming Google access first.  
When you claim access, a cache file with a token is created.

**Comment by AlekzNet** [comment]
Same result:

```txt
DEBUG: Action: permission_write

DEBUG: Action: add_new_task
ERROR: Exception during action: add_new_task
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 115, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 98, in func
    return self.func(instance, *args, **kwargs)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 260, in add_new_task
    self.gui.setController(self.controller)
AttributeError: 'GoogletasksWindow' object has no attribute 'controller'
DEBUG: Running ErrorDialog

```

**Comment by e3rd** [comment]
Thanks, great! I think we may have spotted the issue. Would you mind trying the new version (just replace the main file with the current https://github.com/e3rd/zim-plugin-googletasks/blob/master/googletasks.py )

**Comment by AlekzNet** [comment]
```txt
ERROR: Exception while loading plugin: googletasks
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/__init__.py", line 365, in load_plugins_from_preferences
    self.load_plugin(name)
  File "/usr/lib/python3/dist-packages/zim/plugins/__init__.py", line 466, in load_plugin
    klass = self.get_plugin_class(name)
  File "/usr/lib/python3/dist-packages/zim/plugins/__init__.py", line 420, in get_plugin_class
    mod = get_module(modname)
  File "/usr/lib/python3/dist-packages/zim/utils.py", line 35, in get_module
    mod = __import__(name)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 6
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```
:)

**Comment by AlekzNet** [comment]
Much better now! Testing further!!! Thanks much!

**Comment by AlekzNet** [comment]
OK, I can create new tasks in Google using ZIm, but I do not see them in Zim and I can import tasks created in Google (even for today).

```txt
...
DEBUG: Load extension: <class 'zim.plugins.googletasks.GoogletasksWindow'>
...
DEBUG: Action: import_tasks
DEBUG: URL being requested: GET https://www.googleapis.com/tasks/v1/lists/%40default/tasks?maxResults=999&showCompleted=false&dueMin=2020-05-26T00%3A00%3A00.000Z&dueMax=2020-05-27T00%3A00%3A00.000Z&alt=json
DEBUG: Skipping Another test task for zim.
DEBUG: Skipping Operating system drive.
INFO: Googletasks \ New tasks: 0, page: Tasks
```
For some reason, "Another test task for zim" is skipped.

This is what happens when I created a new task in Zim:

```txt
DEBUG: Action: add_new_task
DEBUG: Opening dialog "Search"
INFO: Running: ('git', 'status', '--porcelain') (cwd: '/home/alekz/Notebooks/Notes')
DEBUG: No autosave version needed - no changes
DEBUG: URL being requested: POST https://www.googleapis.com/tasks/v1/lists/%40default/tasks?alt=json
INFO: Googletasks \ Task 'New task test for today' created.
```
I see it in Google (immediately!), but not in Zim.

**Comment by AlekzNet** [comment]
After restarting Zim I clicked "Import new tasks"

```txt
DEBUG: Action: import_tasks
DEBUG: URL being requested: GET https://www.googleapis.com/tasks/v1/lists/%40default/tasks?maxResults=999&showCompleted=false&dueMin=2020-05-26T00%3A00%3A00.000Z&dueMax=2020-05-27T00%3A00%3A00.000Z&alt=json
INFO: {'kind': 'tasks#task', 'id': 'T3VpLVFHY0NjaDY3ZkhsWA', 'etag': '"MTMwODU3ODU1Mw"', 'title': 'New task test for today', 'updated': '2020-05-25T22:41:18.000Z', 'selfLink': 'https://www.googleapis.com/tasks/v1/lists/MTUyMDAwMjkwNjg2NTUwMzc0Mzg6MDow/tasks/T3VpLVFHY0NjaDY3ZkhsWA', 'position': '00000000000000000000', 'notes': 'New task test for today description', 'status': 'needsAction', 'due': '2020-05-26T00:00:00.000Z'}
DEBUG: Skipping Another test task for zim.
DEBUG: Skipping Operating system drive.
INFO: Googletasks \ New tasks: 1, page: Tasks
DEBUG: Store page: Tasks
```
But nothing appeared in Zim

**Comment by e3rd** [comment]
It says `Skipping` only if the task has already been imported recently into Zim. Cannot it be the case of "Another test task for zim"?

However, it is strange that `{'kind': 'tasks#task', 'id': 'T3VpLVFHY0NjaDY3ZkhsWA', 'etag': '"MTMwODU3ODU1Mw"', 'title': 'New task test for today', 'updated': '2020-05-25T22:41:18.000Z', 'selfLink': 'https://www.googleapis.com/tasks/v1/lists/MTUyMDAwMjkwNjg2NTUwMzc0Mzg6MDow/tasks/T3VpLVFHY0NjaDY3ZkhsWA', 'position': '00000000000000000000', 'notes': 'New task test for today description', 'status': 'needsAction', 'due': '2020-05-26T00:00:00.000Z'}` was not imported into the page Tasks! I'll try to figure this out.

**Comment by e3rd** [comment]
Would you be so kind to try the new version? I've really spotted a bug that might have been responsible for that.

**Comment by AlekzNet** [comment]
Nice one! It's working now! Thanks much! 

When I create a new task for today in ZIm, it immediately appears in Google, but not in Zim.
But when I import tasks it shows up in Zim. Is this how it's supposed to work?

If a task is created in Google, it took me two attempts (with a couple of minutes in between) to get it imported in Zim. Apparently Google also needs some time. 

A Google task `#6` for May 28 (today is May 26) cannot be directly imported, but, I think, it's the correct behaviour, right?

Same for Zim task `#7`for May 29 - it appears in Google, but not in Zim:

```txt
DEBUG: URL being requested: POST https://www.googleapis.com/tasks/v1/lists/%40default/tasks?alt=json
INFO: [Googletasks] Task 'Task #7 for May 29' created.
DEBUG: Action: import_tasks
DEBUG: URL being requested: GET https://www.googleapis.com/tasks/v1/lists/%40default/tasks?maxResults=999&showCompleted=false&dueMin=2020-05-26T00%3A00%3A00.000Z&dueMax=2020-05-27T00%3A00%3A00.000Z&alt=json
DEBUG: Skipping Task #5 for today.
DEBUG: Skipping Task #3 for today.
DEBUG: Skipping Task 2 for today.
DEBUG: Skipping New task test for today.
DEBUG: Skipping Another test task for zm.
DEBUG: Skipping Operating system drive.
INFO: [Googletasks] New tasks: 0, page: Tasks
DEBUG: Action: import_tasks
DEBUG: URL being requested: GET https://www.googleapis.com/tasks/v1/lists/%40default/tasks?maxResults=999&showCompleted=false&dueMin=2020-05-26T00%3A00%3A00.000Z&dueMax=2020-05-27T00%3A00%3A00.000Z&alt=json
DEBUG: Skipping Task #5 for today.
DEBUG: Skipping Task #3 for today.
DEBUG: Skipping Task 2 for today.
DEBUG: Skipping New task test for today.
DEBUG: Skipping Another test task for zm.
DEBUG: Skipping Operating system drive.
INFO: [Googletasks] New tasks: 0, page: Tasks
```

**Comment by AlekzNet** [comment]
Next - task completion. Works perfectly if "checked" in Zim. If "completed" in Google - nothing happens. Tried importing, restarting, running zim --plugin googletasks. 

Also the tasks for other (than today) days still  do not appear in Zim.

**Comment by e3rd** [comment]
> When I create a new task for today in ZIm, it immediately appears in Google, but not in Zim. But when I import tasks it shows up in Zim. Is this how it's supposed to work?

In short, yes. The purpose of the plugin was mainly to allow the user to follow-up its tasks from Zim and use Google Tasks as a mere storage.
So if you start creating a task, tomorrows date is offered. I did not think about the workflow when one would create Google Task for today – instead of that I'm creating my tasks in Zim. And in the moment I want to postpone it to the future, I hit "Task from cursor or selection" and send it to the Google Tasks. Is it in your workflow that today's task should immediately appear in Zim, too? Would you create a new issue here if so?

> If a task is created in Google, it took me two attempts (with a couple of minutes in between) to get it imported in Zim. Apparently Google also needs some time.

That's strange. For me, I can import it instantly every time, no need for waiting. Would you post the debug output again in a new issue preferably?

> A Google task #6 for May 28 (today is May 26) cannot be directly imported, but, I think, it's the correct behaviour, right?

Right! It appears the day May 28. Think of the task due date as "start working on the task no earlier than" rather than "deadline date". Because deadline can be done in Zim with the `<` mark, ex: `[] task with a due date <2020-05-29` (as documented in [Task list](https://zim-wiki.org/manual/Plugins/Task_List.html)). When I hit <key>Alt+X</key>, these due dates show pretty well in Zim.  
Would you prefer the plugin behave another way? We may add some switch on/off in plugin options to change the behaviour.

> Also the tasks for other (than today) days still do not appear in Zim.

Tasks from the past appear just once in Zim. Were these tasks imported before? When run for the first time (so that cache file does not exist), only tasks with today's due date are imported. Other times, all the tasks between current today and the day of the last import (if not imported before) are fetched.

> If "completed" in Google - nothing happens. Tried importing, restarting, running zim --plugin googletasks.

Unfortunately, that's the correct behaviour in the moment. When I mark as complete in Google Tasks, I do not want to bother more with the task in the Zim again. If you have another workflow, describe it in the new issue please.


Thanks for the effort you did to make this plugin better!

**Comment by AlekzNet** [comment]
> The purpose of the plugin was mainly to allow the user to follow-up its tasks from Zim and use Google Tasks as a mere storage.

Aha, got it! Then it works like expected indeed!

>  Is it in your workflow that today's task should immediately appear in Zim, too?
> Think of the task due date as "start working on the task no earlier than" rather than "deadline date".

My idea is to integrate my MSOffice office environment and my Linux home office environment. I use tasks as reminders with no actual information, but rather pointers to the documents. For example, I have a Zim notepad dedicated to projects. One Zim sub-page per project. Each sub-page has tasks/reminders. So in the "Tasks" panel I have a list of tasks, which link me to the actual Zim pages. The idea was to propagate Zim tasks to MSOffice, Google and back, so I can get reminders in all environments. Since there is no actual information in the tasks, there is no security breech. 

> Thanks for the effort you did to make this plugin better!

Thanks much for YOUR efforts! You make our life easier and more pleasant! :)

**Comment by e3rd** [comment]
:)) Great to hear that the plugin works well for you! Tell me if you need some functionality in the future.
