### ISSUE TITLE
Can't insert a checkbox

### ISSUE THREAD

**Issue by AlekzNet** [e3rd/zim-plugin-googletasks#19]
Currently it's impossible to insert a checkbox. This is the error:

```txt
This is zim 0.72.1
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 8, 2, 'final', 0)
PyGObject: (3, 36, 0)

======= Traceback =======
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 115, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 98, in func
    return self.func(instance, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 6262, in insert_checkbox_list
    self._start_bullet(UNCHECKED_BOX)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 6271, in _start_bullet
    buffer.set_bullet(line, bullet_type)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 190, in set_bullet
    self.set_bullet_original(row, bullet, indent=indent)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 187, in set_bullet
    taskid = controller.get_task_id(row)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 564, in get_task_id
    task_anchor_pos = self.readline(line_i).find(TASKANCHOR_SYMBOL)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 554, in readline
    textiter = buffer.get_iter_at_line(line_i)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 2750, in get_iter_at_line
    raise ValueError('Line number beyond the end of the buffer: %i' % line)
ValueError: Line number beyond the end of the buffer: 131
```

Creating new tasks from the plugin is OK.

**Comment by AlekzNet** [comment]
It works if started with `zim --debug --standalone`. Zim crashes when started normally. 

Note: I have multiple Zim Notebooks.

**Comment by e3rd** [comment]
Really strange! Would you be so kind and upload here the very page that makes the error when you try to Insert / Checkbox list?

**Comment by AlekzNet** [comment]
The page itself does not make any difference. I've added a new empty page to a non-default Notebook: - Insert -> Checkbox List crashes Zim immediately. So, I think it's related to multiple notebooks.

**Comment by e3rd** [comment]
Nice! I've been able to simulate this. How did you get the error output, tell me? In my case, `Aborted (core dumped)` is printed out.

**Comment by AlekzNet** [comment]
>  How did you get the error output

Sometimes it crashes with core dump and no message, sometimes it survives and shows a popup. So far I could not find any correlations. Today it always crashes :D

**Comment by e3rd** [comment]
(I'll try to debug this in few days :) )

**Comment by e3rd** [comment]
Would you please check current version whether it works well with multiple notebooks open?

**Comment by AlekzNet** [comment]
Strange, zim 0.73 does not see the plugin at all.

**Comment by AlekzNet** [comment]
```txt
ERROR: Could not load plugin googletasks
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/gui/preferencesdialog.py", line 362, in __init__
    klass = self.plugins.get_plugin_class(key)
  File "/usr/lib/python3/dist-packages/zim/plugins/__init__.py", line 420, in get_plugin_class
    mod = get_module(modname)
  File "/usr/lib/python3/dist-packages/zim/utils.py", line 35, in get_module
    mod = __import__(name)
  File "/home/alekz/.local/share/zim/plugins/googletasks.py", line 16, in <module>
    import jsonpickle
ModuleNotFoundError: No module named 'jsonpickle'
```

**Comment by e3rd** [comment]
I forgot this is an external dependency. Would you ppease try launching
pip3 install jsonpickle?

**Comment by AlekzNet** [comment]
Yes, it's working now! Thanks! But, I don't quite understand the logic.

- I open another Notebook (not Notes)
- In a page called Test I add a check box with a text "Test task"
- I select the text and choose "Task from cursor or selection"
- I fill in the form (the date is today) and click OK
- The selection disappears and no task appears in Zim
- I click "Import new tasks" 
- A new page "Home" got created with the single imported tasks in it. (I do have a separate Tasks page with some tasks)

Is it how it's intended to work?

**Comment by e3rd** [comment]
Yes, that's right! Would you expect the task should stay on the page if you set its date to today (so that you are not using the plugin to postpone the tasks)?

> I do have a separate Tasks page with some tasks

You may easily set up your separate tasks page in the `File / Properties / Page to be updated` :)

**Comment by AlekzNet** [comment]
Is it possible to keep the task on the page where it was created and appear there at the moment where it's created (without additional importing step)? I think it's more logical, but possibly there were other reasons why it was done how it's done :)

**Comment by e3rd** [comment]
> keep the task on the page where it was created 

I did not do this by default because it is difficult to identify the page the task was created in, especially when you are using multiple Zim instances. If task is created in instance ZimA on page P and then you come to the ZimB where there is no page P but you hit import, should the page P be created? Or what should be the behaviour?

> and appear there at the moment where it's created (without additional importing step)

I think Google server tells the task ID in the moment of import so we can put the task back. Should the task be put back if the date was set for today? Or even if the date is in the future? Or should there be a toggle button in the menu so that user can decide the behaviour? Tell me and open for it a new issue please.
