### ISSUE TITLE
Deleting tasks?

### ISSUE THREAD

**Issue by kimsin98** [e3rd/zim-plugin-googletasks#20]
Is there no way to delete created tasks?

**Comment by e3rd** [comment]
Hi, the tasks are marked as done(/not done) when checked(/unchecked) in Zim. If you need to delete them entirely, you may write a pull request (ex: add such option to Tools / Google tasks / Delete task or something). Have a nice day!

**Comment by kimsin98** [comment]
So there is no way to edit or delete tasks through this plugin. That is very cumbersome.
