### ISSUE TITLE
All but one function does not work

### ISSUE THREAD

**Issue by kimsin98** [e3rd/zim-plugin-googletasks#21]
This plugin worked for 1 test task I added through Google Tasks (like the example), then it is completely unusable.

What fails
* Import new task from Google Tasks to Zim: `[Googletasks] No tasks found.`
* Add new task to Zim: No changes to home or anywhere

What works
* Add new task to Google Tasks: Although there is no checkbox in Zim, the task did get added to Google Tasks. However, you cannot interact with it in Zim because import does not work at all.

**Comment by e3rd** [comment]
Hi, do you see some errors in `zim --debug --standalone` that you can post here?

> Although there is no checkbox in Zim, the task did get added to Google Tasks

When it is moved to Google Tasks, it disappears from Zim. When due date comes, its gets re-imported to Zim automatically. How many days you set when postponing the task from Zim to Google Tasks?

**Comment by kimsin98** [comment]
I see. The default date for adding tasks is the next day, which is why nothing worked.

I find it very confusing why you would design it so that only the tasks for the current day would get imported. Not everyone procrastinates until the last day for every task.

The vision (if it exists) of this plugin seems too different from what I have in mind. I will look for my own solution.

**Comment by e3rd** [comment]
Not procrastination but following up, you did not get the purpose of this plugin. If you'd presented the usecase you needed, I might have understood and helped you if that would not mean a loads of work. Good luck.
