### ISSUE TITLE
dateutil error

### ISSUE THREAD

**Issue by Elwood4415** [e3rd/zim-plugin-googletasks#23]
When trying to add the Google Tasks plug-in to Zim, I get the following error:

ERROR: Could not find a version that satisfies the requirement dateutil (from versions: none)
ERROR: No matching distribution found for dateutil

I have attempted to update to the current dateutil, but that doesn't seem to help. Actually, it tells me that I already have the current dateutil. I am attempting this on two different systems. One is Kubuntu and the other is Zorin 17. I get the same error on both systems. Any help would be appreciated.

**Comment by e3rd** [comment]
Will you try
pip install python-dateutil
Or pip3 install python-dateutil
Please? :)

**Comment by Elwood4415** [comment]
Thanks for the quick response!

On the machine with Zorin 17 OS, when I tried _pip install python-dateutil, it comes back_

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil) (1.16.0)
DEPRECATION: python-apt 2.4.0-ubuntu3-zorin1 has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of python-apt or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

On the Zorin machine, with _pip3 install python-dateutil, it comes back_

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil) (1.16.0)
DEPRECATION: python-apt 2.4.0-ubuntu3-zorin1 has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of python-apt or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

On the Kubuntu machine, _pip install python-dateutil_ came back instructing me to use:

sudo apt install python3-pip

That seemed to have added python3-pip

But after moving the files to the Zim plugin folder, I still get the following error

There was a problem loading this plugin in the Zim preferences dialog.

**Comment by e3rd** [comment]
That is a tough one! It might be there is multiple python versions installed on your system. One that is using zim has no link to the dateutil library.

1. Find `zim`

On Ubuntu, it is that way:
```bash
$ whereis zim
zim: /usr/bin/zim /usr/share/zim /usr/share/man/man1/zim.1.gz
```

2. Find the interpreter. AKA what is the first line?

```bash
$ cat zim
#!/usr/bin/python3
...
```

In my case, the interpreter is  `/usr/bin/python3`.

3. Launch the interpreter and try importing the library. This should fail. But my output looks like this:

```bash
$/usr/bin/python3
Python 3.11.6 (...)
>>> import dateutil.parser
>>> dateutil.parser.__path__
['/usr/lib/python3/dist-packages/dateutil/parser']
>>> 
```

4. Then, tell what happened.
We'll try to identify how to install the library to the interpreter needed. You know, one interpreter might use launch `pip`, other `pip3`, other `python3-pip`...

**Comment by Elwood4415** [comment]
Again, thank you for your help. Since I was having so many problems with Zorin, and I was thinking of changing to a different distro anyway, I loaded Budgie Ubuntu. I attempted to install "pip install -r requirements.txt" and it comes back error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

So, I am not sure what to do in this instance. On the other hand, on my computer running Kubuntu, everything loaded and is running well. If you have any insights to the above, they would be appreciated.

**Comment by e3rd** [comment]
I am really glad you're patiently helping me to clean up the installation process. This might be caused by recents changes in the pip installer. Try running:

`pip install -r requirements.txt --break-system-packages`

Nevertheless, I'd like to see the interpreter path from my last post, we might still need it if something's wrong again.

**Comment by Elwood4415** [comment]
I am glad to help in any way that I can. I will attempt to get the information you are requesting tonight (in Illinois, US).

But, I used the break-system-packages command you sent most recently, and it worked. I am up and running Google Tasks in Zim on both computers now.

**Comment by e3rd** [comment]
Great! Nothing is needed, then ✓
